[package]
name = "tcm_security_academy_rust101"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix_lambda = "0.2.0"
