[package]
name = "conditional_statements"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[build-dependencies]
cc = "1.0.69"
gen = "0.0.0"
